version: '3.8'

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://root:secret@db:5432/rate?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/api 

  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: rate
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  data:
